name: Get Daily

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,13 * * *"

env:
  GITHUB_NAME: lesnolie
  GITHUB_EMAIL: lesliezhang08@gmail.com

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

    
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate new daily
        run: |
          python get_daily.py ${{ secrets.G_T }} ${{ github.repository }} ${{ secrets.CICHANG_USER_NAME }} ${{ secrets.CICHANG_PASSWORD }} ${{ secrets.FORST_EMAIL }} ${{ secrets.FORST_PASSWORD }} 
          python main.py ${{ secrets.G_T }} ${{ github.repository }} 

      - name: Push README
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "new daily stats" || echo "no file change"
          git push || echo "no need push"
