name: Get Daily

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,13 * * *"

env:
  GITHUB_NAME: lesnolie
  GITHUB_EMAIL: lesliezhang08@gmail.com

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

    
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Configure pip cache
        uses: actions/cache@v1
        id: pip-cache
        with:
          path: venv
          key: pip-1-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Generate new md
        run: |
          source venv/bin/activate
          python get_daily.py ${{ secrets.G_T }} ${{ github.repository }}
      # Fix for the unsafe repo error: https://github.com/repo-sync/pull-request/issues/84
      - name: Run safe dir
        run: |
          git config --global --add safe.directory /github/workspace
      - name: Push README
        run: |
          date > generated.txt
          git config user.name lesnolie
          git config user.email lesliezhang08@gmail.com
          git add .
          git commit -m "generated"
          git push
